### ISSUE TITLE
Error publishing to sheets

### ISSUE THREAD

**Issue by jsutton78** [bradschm/JSS-Advanced-Search-to-Google-Sheets#1]
So close to getting this to work, but now I get the following error on line 128.

Traceback (most recent call last):
  File "jss-advanced_search-to-google_sheets.py", line 189, in <module>
    publish(report,columns)
  File "jss-advanced_search-to-google_sheets.py", line 128, in publish
    cell_list = worksheet.range('A1:%s%s' % (string.uppercase[number_of_columns],number_of_rows))
IndexError: string index out of range

Any idea what's going on?

**Comment by bradschm** [comment]
Do you have more than 26 columns by chance?

**Comment by jsutton78** [comment]
Nope.  I've even tried an advanced search with only 2 columns to see if that helped, but no luck.

**Comment by bradschm** [comment]
Can you put these two lines above line 128?

print "Number of Columns: %s" % string.uppercase[number_of_columns]
print "Number of Rows: %s" % number_of_rows

**Comment by jsutton78** [comment]
Hmm, now I get:

  File "jss-advanced_search-to-google_sheets.py", line 123, in publish
    print 'Number of Columns: %s' % string.uppercase[number_of_columns]
IndexError: string index out of range

**Comment by bradschm** [comment]
Try this line instead on 123:
print 'Number of Columns: %s' % number_of_columns

**Comment by jsutton78** [comment]
Now back to the original error:

File "jss-advanced_search-to-google_sheets.py", line 131, in publish
    cell_list = worksheet.range('A1:%s%s' % (string.uppercase[number_of_columns],number_of_rows))
IndexError: string index out of range

**Comment by bradschm** [comment]
Was there any output before that? Specifically looking for the lines that should now read: Number of Columns and Number of Rows.

**Comment by bradschm** [comment]
I suspect there is something up with the worksheet object.

**Comment by jsutton78** [comment]
Ahh, yes here it is:

Number of Columns: 26
Number of Rows: 1000

This really makes no sense though, I'm using a test group with only 1 computer object.

**Comment by bradschm** [comment]
Looks like the spreadsheet might contain some data that it's having trouble clearing. Can you try manually clearing the sheet or try a new blank sheet?

Brad Schmidt

**Comment by jsutton78** [comment]
Hey Brad,

I gave that a try, even created a new sheet altogether.  Same error.  And no matter what advanced search ID I use, it's always finding 26 columns and 1000 rows.

**Comment by bradschm** [comment]
At that point it is reading what is existing in the worksheet so it can
clear the way. You could comment out that whole if statement and see what
it does.

**Comment by jsutton78** [comment]
Let me give that a shot.

**Comment by jsutton78** [comment]
So I'm not a python master, but I was able to get this working by changing the following line:

if number_of_columns != 0 and number_of_rows != 0: 
to
if number_of_columns == 0 and number_of_rows == 0:

I ran the script a few times and SUCCESS!

**Comment by bradschm** [comment]
Basically that line is checking to see if it is already cleared. Now it
returns false since neither value is 0 so it skips that section where it
was choking. I'll see if I can replicate the issue. You will want to change
that back so it clears the sheet properly unless it is a one time write or
you don't think the rows returned will ever be less. Maybe now that data is
in, it will clear properly.
